---
- name: configuring the apache server
  hosts: webserver
  become: yes
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: installing the apache packages
      apt:
        name: apache2
        state: present
    - name: starting apache services
      service:
        name: apache2
        state: started
    - name: creating the directory
      file:
        path: /tmp/cal
    - name: Open directory
      copy:
        src: /tmp/cal
        dest: /var/www/html/
    - name: restarting the apache services
      service:
        name: apache2
        state: restarted
